### ISSUE TITLE
Invalid logical modifier presentation

### ISSUE THREAD

**Issue by tormozz48** [bem-sdk/bem-fs-scheme#6]
```
Expected :"common.blocks/block2/_mod2/block2_mod2.js"
Actual   :"common.blocks/block2/_mod2/block2.js"
```

**Comment by tormozz48** [comment]
@tadatuta

**Comment by tadatuta** [comment]
@tormozz48 are you sure?
see passed tests: https://github.com/bem-sdk/bem-fs-scheme/blob/master/test/test.js#L46-L60

**Comment by tormozz48** [comment]
@tadatuta Sorry, I have found bug in my own code. I'll close this issue
