### ISSUE TITLE
What is flat scheme?

### ISSUE THREAD

**Issue by a-x-** [bem-sdk/bem-fs-scheme#7]

**Comment by zxqfox** [comment]
```
blocks/
  block.js
  block.css
  block__elem.js
  block2.js
  block2_mod.js
  block2_mod.css
  etc.
```

**Comment by a-x-** [comment]
Can you place it into readme?

**Comment by zxqfox** [comment]
Please, PR that!

**Comment by skad0** [comment]
> Can you place it into readme?

Do we really need this, when we have it [here](https://en.bem.info/methodology/filestructure/#flat)?

**Comment by a-x-** [comment]
@skad0, ok, what about adding link?

**Comment by a-x-** [comment]
https://github.com/bem-sdk/bem-fs-scheme/pull/8
